### PR TITLE
[Collapsible][Accordion] Add type attribute to accordion button

### LINKED ISSUE #1084: Clicking an AccordionTrigger within a `<form>` triggers the form submission
### Current Behavior
Clicking a trigger submits the form because button `type` is `submit` by default in browsers. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

### Expected behavior
Clicking a trigger should probably not submit the form and should just open/close the accordion panel.

### Reproducible example

[Repro Example](https://codesandbox.io/s/solitary-moon-yzrcy?file=/src/App.tsx)

### Suggested solution
Defaulting the `type` attribute to `button` on the AccordionTrigger would probably solve the issue. This might apply to other trigger primitives as well.

### Your environment

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Radix Package(s) |    Accordion     | 0.1.5        |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |

### PR DESCRIPTION
**Pull request by jjenzz**
Closes #1084

### CODE REVIEW

**Review by andy-hook — APPROVED** [review]

**Comment by andy-hook** [comment]
Should this also be the case for `ToolbarButton` ?

**Review by benoitgrelard — APPROVED** [review]

**Comment by andy-hook** [comment]
> Maybe, although unlikely to have a toolbar in a form?

Yeah probably unlikely. Was thinking along the lines of a content editor in a comment form or something, not sure.

**Comment by benoitgrelard** [comment]
I guess no harm in adding it there too, in any case. It doesn't carry over the issue that the tooltip had.

**Comment by jjenzz** [comment]
Good shout! Added 👍

**Review by benoitgrelard — APPROVED** [review]

**Pull request merged**
