### PR TITLE
Prevent minification

### PR DESCRIPTION
**Pull request by benoitgrelard**
Supersedes #1316 as we have updated parcel since and the option has changed.

### CODE REVIEW

**Comment by benoitgrelard** [comment]
This doesn't seem to cover everything yet still, because it still strips out our dev checks.
I think this is because parcel sets `NODE_ENV` to production by default, as mentioned here: https://parceljs.org/features/production/#development-branch-removal

I still need to find how we do this.

**Comment by benoitgrelard** [comment]
I'm not even sure that `--no-minimize` option is working at all as I can't see any difference between the dist before and after that change 🤔

**Comment by jjenzz** [comment]
just been fiddling with this on a side-project and i'm going `NODE_ENV=development parcel build 'packages/*/*'` for now (in case it helps)

**Comment by benoitgrelard** [comment]
https://parceljs.org/features/node-emulation/#node_env

>  The NODE_ENV environment variable is automatically set by Parcel depending on the mode. When running parcel build, NODE_ENV is set to production by default, otherwise it is set to development. **This can be overridden by setting NODE_ENV yourself (e.g. in your shell).**

So I can override that in our build command

```diff
- "build:packages": "parcel build 'packages/*/*/' --no-cache --no-optimize && yarn build:fix-type-defs",
+ "build:packages": "NODE_ENV=development parcel build 'packages/*/*/' --no-cache --no-optimize && yarn build:fix-type-defs",
```

and it does changes the output, namely this:

image

isn't compiled away, and we can find the warnings in the output.

However, the check is stripped too so that's still not exactly what we want, otherwise when people do end up building their apps, they have no way to get rid of them and they will always remain…

Still looking for a solution…

**Comment by benoitgrelard** [comment]
I've tried this: https://parceljs.org/features/node-emulation/#disabling-these-features
But that doesn't seem to work either.

**Comment by benoitgrelard** [comment]
Created a reduced test-case and opened an issue with parcel: https://github.com/parcel-bundler/parcel/issues/8025

**Pull request closed without merging**
