### PR TITLE
[Avatar] Support referrer policy in AvatarImage

### PR DESCRIPTION
**Pull request by g12i**
### Description

Include referrerPolicy when checking image in `useImageLoadingStatus()`. Fixes: #1616 

In my case the issue occurred with Gmail avatars, served from `googleusercontent.com`. 

image

I added tests which somehow simulate this behaviour. It's hard to add a storybook example without actually using my own image.

### CODE REVIEW

**Comment by franckdsf** [comment]
Hi,
It looks like ``crossOrigin`` isn't spread either. 
Is there a way to include it (for COEP webistes that require ``crossOrigin="anonymous"``) ?
Thank you :)

**Review by chaance — APPROVED** [review]

**Comment by chaance** [comment]
@franckdsf I'm going to merge this as-is. Do you want to open a follow-up PR to address cross-origin issues?

**Comment by g12i** [comment]
HI @chaance, sorry it's been ages since I opened that PR and I didn't notice your update! I'd be happy to open a follow up PR next week.

**Comment by ozgurozalp** [comment]
> @franckdsf I'm going to merge this as-is. Do you want to open a follow-up PR to address cross-origin issues?

I've opened a pull request for that #3261

**Pull request merged**
