### PR TITLE
[DropdownMenu][ContextMenu] Expose `onCloseAutoFocus`

### PR DESCRIPTION
**Pull request by benoitgrelard**
cc @vladmoroz, this should help you resolve your focus troubles once we release new versions.

### CODE REVIEW

**Comment by vladmoroz** [comment]
Thanks, Benoît! Is the plan to release once merged?

**Comment by benoitgrelard** [comment]
> Thanks, Benoît! Is the plan to release once merged?

Yep 👍

**Review by jjenzz — APPROVED** [review]

**Comment by benoitgrelard** [comment]
@vladmoroz I'll ping you once we've released.

**Comment by benoitgrelard** [comment]
Release is done:
image

The prop you’re after is `onCloseAutoFocus` on `DropdownMenu.Content`.
You’ll want to `event.preventDefault` in here when (and only when) you want to do custom focus management.

**Pull request merged**
