### PR TITLE
[Slider] Add chromatic story

### PR DESCRIPTION
**Pull request by benoitgrelard**

### CODE REVIEW

**Review by jjenzz — APPROVED** [review]
Can we add an extra story here with the thumb at `0%` or `100%` please? Means we can see if the thumb offset logic has been broken because it makes sure the thumb edge aligns with the track edge.

All good otherwise :+1:

**Comment by benoitgrelard** [comment]
> Can we add an extra story here with the thumb at `0%` or `100%` please? Means we can see if the thumb offset logic has been broken because it makes sure the thumb edge aligns with the track edge.
> 
> All good otherwise 👍

Good idea, would a single one with 2 thumbs at each extremity suffice?

**Comment by jjenzz** [comment]
Yep, that'd be perfect 🙂

**Comment by benoitgrelard** [comment]
That's done.

**Comment by jjenzz** [comment]
Thanks :+1:

**Pull request merged**
