### PR TITLE
React 18

### PR DESCRIPTION
**Pull request by benoitgrelard**

### CODE REVIEW

**Review by benoitgrelard — COMMENTED** [review]
I've done a pass on it @andy-hook and it seems all good to go for me

**Review by andy-hook — APPROVED** [review]
Looks good to me, should we remove `Polymorphic` entirely in a separate change?

**Comment by benoitgrelard** [comment]
Yep, I was going to do this straight after! You're reading my mind 🙂

**Comment by benoitgrelard** [comment]
#1331

**Comment by apoco** [comment]
Are there plans to publish this fix soon?

**Comment by benoitgrelard** [comment]
Hi @apoco, yes it is planned to be released in the next release in the coming week or two.

**Comment by zenorocha** [comment]
@apoco it's now available in the v1.0 release :D

**Pull request merged**
