### PR TITLE
Update useControllableState.tsx

### PR DESCRIPTION
**Pull request by lifeiscontent**
Fix types for useControllableState

### CODE REVIEW

**Comment by benoitgrelard** [comment]
Hi @lifeiscontent, could you explain what your reasoning behind this PR? What is it intending to fix exactly?

**Comment by lifeiscontent** [comment]
@benoitgrelard the types are lying `T | undefined` should just be `T` and whatever the caller is should be a concrete represenation of the possible states

**Comment by lifeiscontent** [comment]
@benoitgrelard I guess from my perspective, the generic should be `T` undefined should be a part of the definition that is calling the function instead of masking it

**Comment by benoitgrelard** [comment]
I see, thanks for the explanation, we'll take a look if it makes sense to incorporate this at some point.

**Pull request closed without merging**
