### PR TITLE
[Accordion] Patch for TypeError on mismatched prop types when `type='multiple'` and `defaultValue='string'`

### PR DESCRIPTION
**Pull request by hoop71**
### Description

Patch for #958 . Details in issue. Checks `defaultValue` for type to prevent TypeError

### CODE REVIEW

**Comment by jjenzz** [comment]
Agreed, I don't think we should silently "fix" things for people who provide an incorrect API. We should guide them to fix their incorrect implementation.

Since this is an issue for non-TS users only, my vote would be something like:

```jsx
Accordion.propTypes = {
  type(props, propName, componentName) {
    const value = props.value || props.defaultValue; 
    if (props.type === 'multiple' && value && !Array.isArray(value)) {
      return new Error('Invalid prop \`type\` of value \`${props.type}\` supplied to \`${componentName}\`. Expects \`single\` when `defaultValue` or `value` prop is type \`string\`.
    }
  },
};
```

**Comment by jjenzz** [comment]
> my brain sees it kinda backwards from that, that instead of validating the type, it would be validating the `defaultValue or `value`

I thought that too initially but then you have two separate prop type validators, this seems less boilerplate.

```jsx
Accordion.propTypes = {
  value(props) {
    if(props.type === 'multiple' && typeof props.value === 'string') {
      // error
    }
    if(props.type === 'single' && Array.isArray(props.value)) {
      // error
    }
  },
  defaultValue(props) {
    if(props.type === 'multiple' && typeof props.value === 'string') {
      // error
    }
    if(props.type === 'single' && Array.isArray(props.value)) {
      // error
    }
  },
};
```

Obviously we can abstract the validator into a validator function but the alternative I provided avoids abstraction and achieves the same thing.

**Comment by hoop71** [comment]
All works for me. Thanks for quick response and sharing the thinking of the library on this minor issue. Changes pushed!

**Comment by hoop71** [comment]
> Sorry for the delay, thanks for this @hoop71 !

Glad to contribute!

**Pull request merged**
