### PR TITLE
[Slider] Allow visual inversion

### LINKED ISSUE #1635: [Slider] Prop to flip direction of values in vertical orientation
### Overview
This is feature request concerning the Slider Primitive
When the current slider is in vertical orientation, value = 0 is at the bottom of the slider, while value = max is at the top. 

It would be great to have an option of switch the direction, so that value = 0 is at the top of the slider and value = max is at the bottom. 

There is currently a prop on Slider.Root to switch the direction on the slider if it is horizontal, (dir = rtl or ltr), it would be useful to have the same but for vertical! 

### Who does this impact? Who is this for?
I'm asking because I need it. My app has an array of cards, and a slider that focuses each card as it moves down. However, because the direction of the slider is the way it is, I need to do some Math to make the position of the thumb align to the card that is focuses. I'll link a prototype below. The relevant slider code starts on line 35
https://replit.com/join/ofcqsnrbeg-cyberspaceline

I think, however, it would be useful for anyone who would like a vertical slider. It's just a little extra confusing to the use the value output of the slider when it's backwards!

### Additional context

Thank you for all your hard work I appreciate it :D

### PR DESCRIPTION
**Pull request by benoitgrelard**
Closes #1635

### CODE REVIEW

**Review by andy-hook — COMMENTED** [review]
Code looks great! super clear and easy to follow 🎉 

Only question would be about the stories:
- Thoughts on adding RTL for the vertical orientation on inversions? (if only for completeness when user testing, we might feel this redundant given you already omitted though)
- Can we add the new inversion case/s to the chromatic stories?

**Comment by andy-hook** [comment]
> For vertical, dir shouldn't have any impact, but I guess we might want that to double check?

Yeah that was my thinking but I checked out the branch just to make sure, figured it might be useful to have around for future manual tests but no biggie.

**Comment by benoitgrelard** [comment]
I'm now using the thumb with the value in everywhere, makes it easier to read I feel.
I'll let you review the Chromatic story change in Chromatic, obviously will all look quite different, but I've just inserted the "Insertions" block almost at the end.

**Review by andy-hook — APPROVED** [review]
Great stuff

**Pull request merged**
