### PR TITLE
[ScrollArea] Add `Presence` to `ScrollThumb`

### PR DESCRIPTION
**Pull request by bukinoshita**
### Description

Added `Presence` to `ScrollThumb`. Closes https://github.com/radix-ui/primitives/issues/1050

### CODE REVIEW

**Comment by benoitgrelard** [comment]
I think here you can simply add the new animation code directly to `thumbClass`.

Would you mind updating the name whilst you're here too?

```tsx
- const THUMB_NAME = 'ScrollbarThumb';
+ const THUMB_NAME = 'ScrollAreaThumb';
```

🙏

**Comment by benoitgrelard** [comment]
> For the Storybook, we use [this component](https://github.com/radix-ui/primitives/blob/main/packages/react/scroll-area/src/ScrollArea.stories.tsx#L358-L377). I want to pass the animated class only for the [ScrollThumb](https://github.com/radix-ui/primitives/blob/main/packages/react/scroll-area/src/ScrollArea.stories.tsx#L367). What's recommended here? Add a new prop like scrollThumbClass and then <ScrollArea.Thumb className={scrollThumbClass ? scrollThumbClass() : thumbClass()} />?

Ah, I see what you're saying now, it might be good to only have the animation in the `Animated` story as otherwise all the chromatic stories won't see the thumb as it starts invisible because of the animation.

We usually don't have abstractions like this in stories, but it can happen.

In this case, I would say pass a `animated` prop to `ScrollAreaStory` and default it to `false` and only pass it to `true` in the `Animated` story.

**Comment by bukinoshita** [comment]
> > For the Storybook, we use [this component](https://github.com/radix-ui/primitives/blob/main/packages/react/scroll-area/src/ScrollArea.stories.tsx#L358-L377). I want to pass the animated class only for the [ScrollThumb](https://github.com/radix-ui/primitives/blob/main/packages/react/scroll-area/src/ScrollArea.stories.tsx#L367). What's recommended here? Add a new prop like scrollThumbClass and then <ScrollArea.Thumb className={scrollThumbClass ? scrollThumbClass() : thumbClass()} />?
> 
> Ah, I see what you're saying now, it might be good to only have the animation in the `Animated` story as otherwise all the chromatic stories won't see the thumb as it starts invisible because of the animation.
> 
> We usually don't have abstractions like this in stories, but it can happen.
> 
> In this case, I would say pass a `animated` prop to `ScrollAreaStory` and default it to `false` and only pass it to `true` in the `Animated` story.

Done!

**Comment by jjenzz** [comment]
@benoitgrelard usually when we wrapped `Presence` we would create an `Impl` part to prevent all the hook logic etc. running unnecessarily when it isn't mounted. it looks like that was forgotten here.

**Comment by benoitgrelard** [comment]
That's a good point. Looking at the codebase, it seems there are other places we haven't done it (like `RadioGroupIndicator`, though arguably simple/nothing running there) but `ScrollAreaThumb` is reasonably complex that it should do it 👍

**Pull request merged**
