### PR TITLE
Adds React 19 RC and React-DOM 19 RC to the list of peer dependencies

### PR DESCRIPTION
**Pull request by BenAHammond**

### CODE REVIEW

**Comment by vladmoroz** [comment]
Thanks @BenAHammond, could you go throw "Tracking version changes" step mentioned in the [release process](https://github.com/radix-ui/primitives/blob/main/release-process.md) and note each primitive package change as a patch? We'll be able to merge the PR then.

**Review by vladmoroz — APPROVED** [review]

**Comment by BenAHammond** [comment]
> Thanks @BenAHammond, could you go throw "Tracking version changes" step mentioned in the [release process](https://github.com/radix-ui/primitives/blob/main/release-process.md) and note each primitive package change as a patch? We'll be able to merge the PR then.

Interestingly those instructions aren't working for me. I see files generated: 
```
ls .yarn/versions/
1f1ba8b4.yml	2ab74363.yml	5793010b.yml	60c2f256.yml	75dcd823.yml	c9fc51b8.yml	dc4b1017.yml	ded3a040.yml	eb020608.yml	f4333956.yml
261663d9.yml	54d1ffa8.yml	58957da5.yml	70d7cf62.yml	b20a66e3.yml	d226e89e.yml	dd1eb89d.yml	e97b6ff3.yml	efa9f1f5.yml	fad3e42d.yml
```

but there's nothing to add in git? I'm guessing this is a `.gitignore` setting or I am doing something wrong:

```
git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by vladmoroz** [comment]
Not sure, out gitignore is set up to _not_ ignore `.yarn/versions`. Anyway, I've pushed version updates to your branch and will merge now.

**Comment by BenAHammond** [comment]
Thank you!

**Comment by kamami** [comment]
What about @radix-ui/react-icons?
It still has "react": "^16.x || ^17.x || ^18.x" as a peerDependency.

**Comment by lynixiox** [comment]
Yes I am in the same boat as @kamami . Currently upgrading project to Nextjs 15 with React 19 and getting this issue.

**Comment by takefy-dev** [comment]
same

**Comment by Enzo-PVsyst** [comment]
Same here, any idea on how to upgrade to next 15 that depends on react 19 ? Can't end the update with this package  @radix-ui/react-icons

**Comment by patronconsultoriadeti** [comment]
React 19 help

**Comment by rogueturnip** [comment]
I'm going to pile on here.  There were no problems in the canary releases of Next 15 but as soon as updating to 15.0.1 the following starts to appear (this is with SelectPrimative.Icon but shows with other components too).

Functionally things still work but it's a typescript mess.
```
'SelectPrimitive.Icon' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<SelectIconProps & RefAttributes<HTMLSpanElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<SelectIconProps & RefAttributes<HTMLSpanElement>>' is not assignable to type '(props: any) => ReactNode'.
      Type 'React.ReactNode' is not assignable to type 'import("/-------/node_modules/@types/react/index").ReactNode'.ts(2786)
```

**Comment by alexisdrakopoulos** [comment]
Any update to the @radix-ui/react-icons?

**Comment by moesaif** [comment]
help

**Pull request merged**
