### PR TITLE
Popper core: Expose translateX and translateY as variables

### PR DESCRIPTION
**Pull request by buzinas**
### Description

Hi, Modulz team! First, thanks for this excellent library.

I'm currently working on a project that I need to control the popover a bit more than this package needs. I made this proposed change on `index.module.js` and I'm using `patch-package` to keep them over builds etc, but I thought that I could submit it to upstream and maybe get it merged.

This change just exposes internal `translateX` and `translateY` that can then be used down the tree.

### CODE REVIEW

**Comment by jjenzz** [comment]
Hi @buzinas  👋

Our popper package is not meant for public consumption so it only contains boilerplate/logic that is required to support our primitives. I'm curious what your use-case is here and why you've needed to resort to using our private utilities?

**Comment by benoitgrelard** [comment]
> Thanks for the quick response, @jjenzz.
> 
> I'm using `@radix-ui/react-dropdown-menu` and `@radix-ui/react-popover`, both use `@radix-ui/react-popper` under the hood. They have an `align` prop that you can pass `start`, `center`, `end`, but I need a bit more control than that.
> 
> My specific use case is that, sometimes, I need to open a popover that starts at the bottom of the page (slide pop-up), or at the right of the page (sidebar) etc. I could create more `align` variants, but it seemed that exposing the position as CSS properties is just easier and lets the user smoothly control the position when they need.
> 
> I'm using `patch-package` for that, but thought that wouldn't hurt to open a PR upstream.

Hey @buzinas, I'm not sure I fully understand what you're doing. Would you be able to create a quick demo of what you are doing in codesandbox?

**Comment by buzinas** [comment]
@benoitgrelard 

Normal popover, with `align="start"`: ✅ 

image

"Full" popover that I'm assuming it's impossible to reach with `radix-ui/react-popover` today: 🚫 

image

With the proposed change, I can just do something like:

```js
{
  marginLeft: 'calc(var(--radix-popper-translate-x) * -1)',
}
```

This is just an example, but there are many things I can control when I have the popover position available.

**Comment by benoitgrelard** [comment]
Not sure if you saw but there are some offset props that you can use to offset a particular axis.
`sideOffset` and `alignOffset`. In your case I think you'd be after the `alignOffset`.

From the docs:
image

That said, it's interesting looking at your UI, it looks like perhaps `Popover` would not necessarily be the right component for what you're building (a navigation).

@andy-hook is currently building a new navigation primitive which looks like it would serve your needs much better.

**Comment by buzinas** [comment]
Yeah, I'm using `alignOffset` in some other parts of the application, but since I don't know what the offset is without knowing where the component is located (and I don't want to use a `ref` + effect for that), it was why I decided to expose the position as a CSS property that I can then use.

I understand that my use case isn't very usual though.

**Comment by benoitgrelard** [comment]
Hi @buzinas, as you say I think the use case is a bit unusual, and as I pointed out probably not the right primitive for this even in terms of accessibility.

I will close the issue for now but feel free to keep your patch and we will ping you when our navigation/hover menu primitive is out which I think is more what you are after.

Thanks!

**Comment by andy-hook** [comment]
@buzinas – Just to add more context regarding the navigation primitive, we have a rough outline [here](https://github.com/radix-ui/primitives/issues/823). As @benoitgrelard mentioned this looks to be a good candidate for your use case. We'll keep you in mind after we've released.

**Pull request closed without merging**
