### PR TITLE
[DropdownMenu] Focus last Item on ArrowUp on Trigger

### PR DESCRIPTION
**Pull request by luisorbaiceta**
### Description

As described in the WAI-Aria pattern, dropdown should open and focus last item, when `ArrowUp` on `Trigger`

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
Tests were failing for `RTL` mode. I've fixed that and refactored a bit too. Hope this is fine

**Comment by luisorbaiceta** [comment]
I've provided a `focusLast` option to the `RovingFocus` component and used that to implement the desired behaviour in `Menu`. For this to take effect I have finally added the `ArrowUp` to the `DropdownMenu` component `keyDown` event. Hope this makes sense

**Review by benoitgrelard — COMMENTED** [review]
Hey @luisorbaiceta,

Thanks for looking into this! It's been on our list for a while but we hadn't had a chance to get to it. Great job on the tests too! ♥️ it!

Whilst this works, there are a few things that bother me:
- I don't know if it should be implemented at the `RovingFocusGroup` level, given that it isn't really a requirement for itself. In my mind, it's more a requirement of `DropdownMenu` itself so I feel like it would be better implemented there if we could.
- Doing so right now sort of mutates what `onEntryFocus` does depending on that new `focusLast` prop, so we end up with this comment for example:
```tsx
onEntryFocus={(event) => {
  // only focus first item when using keyboard
```
even though in reality, it might have been a focus last…

What do you think? Did you have any of these nagging feelings in the back of your mind when implementing it?

**Comment by luisorbaiceta** [comment]
> What do you think? Did you have any of these nagging feelings in the back of your mind when implementing it?

Totally. I was hoping for some direction here, but didn't seem polite to ask before trying.

I went for the `RovingFocusGroup` because the focus of the first item in the group was happening there and it seemed correct to not separate them. Maybe focus first item behaviour should be removed too and provide a way to implement that by the consumer?

Do you think this should be implemented in the `DropdownMenu` (right now it only handles the opening part), or should this work be done in the underlying `Menu` component?

Thanks a lot for the feedback @benoitgrelard!

**Comment by benoitgrelard** [comment]
> I went for the RovingFocusGroup because the focus of the first item in the group was happening there and it seemed correct to not separate them.

Yeah that makes sense as a first instinct, my brain went there first too.

> Maybe focus first item behaviour should be removed too

This one is really part of our `RovingFocusGroup` implementation because that's how we manage re-directing focus from the group wrapper to the first item, which is what should happen (ie. the group should not be focused).

> Do you think this should be implemented in the DropdownMenu (right now it only handles the opening part), or should this work be done in the underlying Menu component?

My gut feel is telling me it should belong to `DropdownMenu` because it only is a feature there when considering `DropdownMenu` and `ContextMenu`. That would work if we then build `Menubar` from `DropdownMenu` but it wouldn't work if we build `Menubar` from `Menu` directly. So I guess it depends on the direction we end up taking there.

**Comment by jjenzz** [comment]
@luisorbaiceta Benoit has reminded me separately that the [up arrow functionality is optional](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-13) in the spec and as you have discovered, it's not a 5 min task to figure out how to tackle this problem which is why we had omitted it initially. 

Perhaps best to leave this out for now and we can tackle it later when we have some more time to think about all of this.

**Comment by luisorbaiceta** [comment]
Great! I'll leave this for now.

Just one last word. I was thinking that maybe, to avoid separating this behaviour, `RovingFocusGroup` could provide the list of focus candidates to the `onEntryFocus` function so people could prevent the original focus first and customize its behaviour

**Comment by benoitgrelard** [comment]
> Just one last word. I was thinking that maybe, to avoid separating this behaviour, `RovingFocusGroup` could provide the list of focus candidates to the `onEntryFocus` function so people could prevent the original focus first and customize its behaviour

That's not a bad shout conceptually. Then potentially we could expose `onEntryFocus` to `Menu.Content` and implement only in `DropdownMenu`.

We'll do a bit more thinking about this, for now yeah we can ignore and keep going with the `Menubar` stuff and layer that one after.

**Comment by benoitgrelard** [comment]
Hi @luisorbaiceta we'll close this PR for now as we're not focusing on this.

**Comment by jjenzz** [comment]
curious why radix team is closing things that aren't being focused on? should consumers avoid raising feature requests?

**Comment by benoitgrelard** [comment]
Re-captured as a ticket here: #1319

**Pull request closed without merging**
